### ISSUE TITLE
Authentication not working after service created

### ISSUE THREAD

**Issue by chrisumbel** [Azure/meta-azure-service-broker#62] opened 2016-11-18 13:13 UTC
When I create a service with a "sqlServerParamerters" configuration section like:

		"location": "eastus",
		"properties": {
			"administratorLogin": "admin",
			"administratorLoginPassword": "P455w0rd"
		}

my login is denied with those credentials.

If I inspect my VCAP_SERVICES for a service binding to this service "administratorLogin" and "administratorLoginPassword" are shown to be present in the JSON, but null.

**Comment by bingosummer** [comment] 2016-11-21 06:21
Thanks @chrisumbel for reporting this.
@zhongyi-zhang please help to investigate.

**Comment by zhongyi-zhang** [comment] 2016-11-21 07:17
Hi Chris,
I tried the configuration below,
```
{
    "resourceGroup": "******",
    "location": "westus",
    "sqlServerName": "*******",
    "sqlServerCreateIfNotExist": true,
    "sqlServerParameters": {
        "allowSqlServerFirewallRule": {
            "ruleName": "new rule",
            "startIpAddress": "0.0.0.0",
            "endIpAddress": "255.255.255.255"
        },
        "location": "westus",
        "properties": {
            "administratorLogin": "azure",
            "administratorLoginPassword": "P455w0rd"
        }
    },
    "sqldbName": "*****",
    "sqldbParameters": {
        "location": "westus",
        "properties": {
            "collation": "SQL_Latin1_General_CP1_CI_AS"
        }
    }
}
```
then got the binding result below:
```
"VCAP_SERVICES": {
  "azure-sqldb": [
   {
    "credentials": {
     "administratorLogin": "azure",
     "administratorLoginPassword": "P455w0rd",
     "jdbcUrl": "jdbc:sqlserver://********.database.windows.net:1433;database=******;user=azure;password=P455w0rd",
     "sqlServerName": "*******",
     "sqldbName": "********"
    },
    "label": "azure-sqldb",
    "name": "mysqldb",
    "plan": "basic",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}
```
Those two are not null.
Sorry about that we can't reproduce it. Could you provide some steps to repro?
Thanks!

**Comment by chrisumbel** [comment] 2016-11-22 12:37
I'm working with a customer on this one. I'll get the full config with redacted sensitive information and show you the entire creating/binding process.

**Comment by bingosummer** [comment] 2016-11-29 03:20
@chrisumbel Any updates?

**Comment by bingosummer** [comment] 2016-12-01 23:35
@chrisumbel 

FYI: To enable the debugging option, you can refer to https://github.com/Azure/meta-azure-service-broker/blob/master/docs/how-admin-deploy-the-broker.md#debug-logging.

**Comment by chrisumbel** [comment] 2016-12-02 01:25
We've engaged support and they've reproduced the issue and are working with us. Going to close this issue.

**Comment by bingosummer** [comment] 2016-12-02 02:17
That's good. If anything I can help, please involve me in the support ticket.

**Comment by bingosummer** [comment] 2017-03-09 06:52
I think, the issue has been resolved. Do you feel comfortable to close it?

**Comment by bingosummer** [comment] 2017-05-16 05:55
Closing it. Feel free to re-open it if you still hit it.

**Closed by bingosummer** 2017-05-16 05:55 UTC
